### ISSUE TITLE
yamljs not set as a dependency? Error when running

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/frontend-buildkit#12]
```
Error: Cannot find module 'yamljs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/zach/Desktop/WebDev/Projects/orangeline/tasks/compile-hbs.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by zachwise** [comment]
Looks like this commit fixes the problem 6a935af6e1cb39c704aed259a62f651d1860bdb0
